import React from "react";
import { Activity, Radio, AlertTriangle, ShieldCheck } from "lucide-react";
import { SourceBadge } from "./SourceBadge";

interface DeviceHealthCardProps {
  sensors: any;
}

export function DeviceHealthCard({ sensors }: DeviceHealthCardProps) {
  const health = sensors?.health_status || "HEALTHY";
  const source = sensors?.soil_moisture?.source || "SIMULATION";
  const isSim = source === "SIMULATION";

  return (
    <div style={{ background: "white", padding: "20px", borderRadius: "14px", border: "1px solid #E2E8F0" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "14px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          <Activity size={18} color="#059669" />
          <h3 style={{ fontSize: "1rem", fontWeight: 800, margin: 0, color: "#0F172A" }}>Device & Sensor Telemetry</h3>
        </div>
        <SourceBadge source={source} />
      </div>

      {isSim && (
        <div style={{ padding: "10px 14px", borderRadius: "8px", background: "#FFFBEB", border: "1px solid #FCD34D", color: "#B45309", fontSize: "0.78rem", fontWeight: 700, marginBottom: "14px", display: "flex", alignItems: "center", gap: "8px" }}>
          <AlertTriangle size={16} />
          <span>SIMULATION MODE: Readings generated by device simulator (`simulate_device.py`).</span>
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", fontSize: "0.82rem" }}>
        <div style={{ padding: "10px", background: "#F8FAFC", borderRadius: "8px" }}>
          <span style={{ color: "#64748B", fontSize: "0.7rem", fontWeight: 700 }}>SOIL MOISTURE</span>
          <div style={{ fontSize: "1.1rem", fontWeight: 800, color: "#0F172A", marginTop: "2px" }}>
            {sensors?.soil_moisture?.value ?? 24}%
          </div>
        </div>

        <div style={{ padding: "10px", background: "#F8FAFC", borderRadius: "8px" }}>
          <span style={{ color: "#64748B", fontSize: "0.7rem", fontWeight: 700 }}>AIR TEMPERATURE</span>
          <div style={{ fontSize: "1.1rem", fontWeight: 800, color: "#0F172A", marginTop: "2px" }}>
            {sensors?.temperature?.value ?? 30}°C
          </div>
        </div>

        <div style={{ padding: "10px", background: "#F8FAFC", borderRadius: "8px" }}>
          <span style={{ color: "#64748B", fontSize: "0.7rem", fontWeight: 700 }}>AIR HUMIDITY</span>
          <div style={{ fontSize: "1.1rem", fontWeight: 800, color: "#0F172A", marginTop: "2px" }}>
            {sensors?.humidity?.value ?? 65}%
          </div>
        </div>

        <div style={{ padding: "10px", background: "#F8FAFC", borderRadius: "8px" }}>
          <span style={{ color: "#64748B", fontSize: "0.7rem", fontWeight: 700 }}>TELEMETRY STATUS</span>
          <div style={{ fontSize: "0.88rem", fontWeight: 800, color: "#047857", marginTop: "2px" }}>
            {health}
          </div>
        </div>
      </div>

      <div style={{ marginTop: "14px", paddingTop: "10px", borderTop: "1px solid #F1F5F9", fontSize: "0.72rem", color: "#64748B", display: "flex", justifyContent: "space-between" }}>
        <span>ESP32 Firmware Pipeline: ✓ Ready</span>
        <span style={{ color: "#D97706", fontWeight: 700 }}>Physical Hardware: ⚠ Verification Pending</span>
      </div>
    </div>
  );
}
